# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  blink-cmp-latex = {
    pname = "blink-cmp-latex";
    version = "3a958361e275bb5996e8393e7b2595b2f40c15ca";
    src = fetchFromGitHub {
      owner = "erooke";
      repo = "blink-cmp-latex";
      rev = "3a958361e275bb5996e8393e7b2595b2f40c15ca";
      fetchSubmodules = false;
      sha256 = "sha256-uL3yKHIE2VgQUYZIKl4PFOrccluywSI3ofhZaiUN5rg=";
    };
    date = "2025-05-30";
  };
  emacs-plus = {
    pname = "emacs-plus";
    version = "3e95d573d5f13aba7808193b66312b38a7c66851";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "3e95d573d5f13aba7808193b66312b38a7c66851";
      fetchSubmodules = false;
      sha256 = "sha256-Eepinxv05Yl79AoPVJveGDZPKHhlAes7XtUvrssflrU=";
    };
    date = "2025-03-31";
  };
  ott-vim = {
    pname = "ott-vim";
    version = "911c930743357f9419869def1839257a4814e53b";
    src = fetchFromGitHub {
      owner = "tsung-ju";
      repo = "ott-vim";
      rev = "911c930743357f9419869def1839257a4814e53b";
      fetchSubmodules = false;
      sha256 = "sha256-YyvFIllM5mqrCbvUO6coevHfwhHuC/DYg1Ys1ELL0B4=";
    };
    date = "2024-08-17";
  };
  sbarlua = {
    pname = "sbarlua";
    version = "437bd2031da38ccda75827cb7548e7baa4aa9978";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "437bd2031da38ccda75827cb7548e7baa4aa9978";
      fetchSubmodules = false;
      sha256 = "sha256-F0UfNxHM389GhiPQ6/GFbeKQq5EvpiqQdvyf7ygzkPg=";
    };
    date = "2024-08-12";
  };
}
